/* eslint-disable @next/next/no-css-tags */
/* eslint-disable @next/next/no-page-custom-font */
/* eslint-disable @next/next/no-sync-scripts */
import React, { useState } from "react";
import Head from 'next/head'
import { Inter } from 'next/font/google'
import Header from '../components/Header';
import MintForm from '../components/MintForm';
import Footer from "@/components/Footer";



const inter = Inter({ subsets: ['latin'] })


export default function Mint() {

  return (
      <><Head>
      <title>Nifty Row - Mint New Asset</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/Nifty-iconsm.png" />
      <link rel="preconnect" href="https://fonts.googleapis.com/"></link>
      <link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin></link>
      <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;700&amp;family=Poppins:wght@400;500;700&amp;display=swap"></link>

      <link rel="stylesheet" type="text/css" href="static/vendor/font-awesome/css/all.min.css"></link>
      <link rel="stylesheet" type="text/css" href="static/vendor/bootstrap-icons/bootstrap-icons.css"></link>
      <link rel="stylesheet" type="text/css" href="static/vendor/flatpickr/css/flatpickr.min.css"></link>
      <link rel="stylesheet" type="text/css" href="static/vendor/choices/css/choices.min.css"></link>
      <link rel="stylesheet" type="text/css" href="static/vendor/tiny-slider/tiny-slider.css"></link>
      <link rel="stylesheet" type="text/css" href="static/vendor/nouislider/nouislider.css"></link>
      <link rel="stylesheet" href="/static/css/style.css" />

    </Head><div className="container">
        <Header />
        <section className="pt-4 pt-md-5 pb-0">
          <div className="container">
            <div className="row">
              <div className="col-12 mx-auto text-center">
                <h1 className="fs-2 mb-2">Mint New NFT</h1>
                {/* <p className="mb-0">Praise effects wish change way and any wanted. Lively use looked latter regard had.</p> */}
              </div>
            </div>
          </div>
        </section>
        <MintForm />
        <Footer />
      </div><script src="/static/js/jquery.min.js"></script><script src="/static/js/bootstrap.min.js"></script><script src="static/vendor/bootstrap/dist/js/bootstrap.bundle.min.js"></script><script src="static/vendor/tiny-slider/tiny-slider.js"></script><script src="static/vendor/glightbox/js/glightbox.js"></script><script src="static/vendor/flatpickr/js/flatpickr.min.js"></script><script src="static/vendor/choices/js/choices.min.js"></script></>
  )
}
