/* eslint-disable @next/next/no-img-element */
/* eslint-disable @next/next/no-css-tags */
/* eslint-disable @next/next/no-page-custom-font */
/* eslint-disable @next/next/no-sync-scripts */
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '@/components/Header';
import Hero from '@/components/Hero';
import Footer from '@/components/Footer';
import NFTCard from '@/components/NFTCard';
import { useRouter } from "next/router";
import { useState, useEffect } from "react";


export default function MarketPlace() {
    const router = useRouter();
    const { category = "all", type = "all" } = router.query;
    const [data, setData] = useState([]);

    useEffect(() => {
        async function fetchData() {
        const response = await fetch(`http://localhost:5000/api/nft/allNfts`);
        const data = await response.json();
        console.log(data);
        setData(data);
    }
        fetchData();
    }, [category, type]);

  return (
    <>
    <Head>
        <title>Nifty Row - Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <Header />
    <Hero />
    <section className="pt-0">
        <div className="container">
            <div className="row mb-4 p-4">
                <div className="col-12 text-center">
                    <h2 className="mb-0">NFT MarketPlace</h2>
                </div>
            </div>
            <div className="row g-4">
                {data.map(nft => (
                    <NFTCard key={nft.id} nft={nft} />
                ))}
            </div>
        </div>
    </section>
        
    </>
  )
}
